name: merge ci

on: [pull request]
  push:
    branches:
      - main  
jobs:
      runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v2
      - run: echo "the job was autoatically triggered by a $({github.event_name})"
      - run: python.main